# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:43:19+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union
from uuid import UUID

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBearer
from fastapi import Header, Path, Query
from pydantic import conint

from models import (
    AddForwardedPortSettings,
    AgentResponse,
    ApiV1AgentTelemetryPostRequest,
    ApiV1AgentTelemetryStandalonePostRequest,
    ApiV1EnvironmentsEnvironmentIdFolderPatchResponse,
    ApiV1EnvironmentsEnvironmentIdPatchResponse,
    ApiV1EnvironmentsGetResponse,
    ApiV1PoolsDefaultGetResponse,
    ApiV1SasGetResponse,
    ApiV1SecretsGetResponse,
    ApiV1TenantTenantIdPoolPoolNameVmGetResponse,
    BillSummary,
    ChangeResourceDeletionRequestBody,
    ClaimVMBody,
    CloudEnvironmentFolderBody,
    CloudEnvironmentResult,
    CreateCloudEnvironmentBody,
    CreateEnvironmentPoolResourceBody,
    CreateEnvironmentStateChangeBody,
    CreateOrUpdatePoolBody,
    CreatePoolGroupBody,
    CreatePrebuildTemplateBody,
    CreateTemplateResult,
    DeletePrebuildTemplatesBody,
    EnvironmentRegistrationCallbackBody,
    EnvironmentStateChange,
    HeartBeatBody,
    IssueDelegatePlanAccessTokenBody,
    LocationInfoResult,
    LocationsResult,
    MessageCodes,
    NetworkSettingsResource,
    NetworkSettingsResourceList,
    NotificationDataBody,
    PlanResource,
    PlanResourceHeaders,
    PlanResourceList,
    PlanResourceUpdateBody,
    PoolConfigRequestBody,
    PoolDefinitionInput,
    PoolGroupResult,
    PoolResult,
    PoolSettingsBody,
    PrebuildReadinessResult,
    PrebuildTemplateInfoResult,
    ProblemDetails,
    RefreshProfileTelemetryPropertiesRequest,
    RefreshProfileTelemetryPropertiesResponse,
    ReplayBillRequestBody,
    RPSubscriptionNotification,
    ScopedCreateSecretBody,
    ScopedSecretResultBody,
    ScopedUpdateSecretBody,
    SecretScope,
    SkuName,
    StorageType,
    SystemConfigurationResponse,
    TenantInfoResult,
    TunnelPortInfoResult,
    UnderInvestigationResponseBody,
    UnfilteredCloudEnvironmentResult,
    UpdateCloudEnvironmentBody,
    UpdatePoolGroupBody,
    UpdatePrebuildTemplateBody,
    UpdatePrebuildTemplateVersionsBody,
    UpdateSystemConfigurationBody,
    UpdateUserSecretsRequestBody,
    VmLogsUploadInfo,
    VMResult,
)

app = MCPProxy(
    description='Public APIs for managing VS Codespaces',
    title='VSOnline',
    version='v1',
    servers=[{'url': 'https://online.visualstudio.com'}],
)


@app.post(
    '/api/v1/AgentTelemetry',
    tags=['telemetry_operations', 'profile_telemetry_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__agent_telemetry(body: ApiV1AgentTelemetryPostRequest = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/AgentTelemetry/standalone',
    tags=['telemetry_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__agent_telemetry_standalone(
    body: ApiV1AgentTelemetryStandalonePostRequest = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Agents/{family}',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__agents__family(family: str):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Environments',
    tags=['location_info_services', 'plan_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__environments(
    name: Optional[str] = None,
    plan_id: Optional[str] = Query(None, alias='planId'),
    deleted: Optional[bool] = False,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Environments',
    tags=['environment_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__environments(
    access: Optional[bool] = None, body: CreateCloudEnvironmentBody = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/Environments/{environmentId}',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__environments__environment_id(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Environments/{environmentId}',
    tags=[
        'environment_management',
        'environment_ports_management',
        'environment_routes_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_environment_route(
    environment_id: UUID = Path(..., alias='environmentId'),
    connect: Optional[bool] = None,
    pf_connect: Optional[bool] = Query(None, alias='pfConnect'),
    deleted: Optional[bool] = False,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/Environments/{environmentId}',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_api_v1__environments__environment_id(
    environment_id: str = Path(..., alias='environmentId'),
    body: UpdateCloudEnvironmentBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Environments/{environmentId}/_callback',
    tags=['environment_management', 'environment_routes_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_environment_route(
    environment_id: str = Path(..., alias='environmentId'),
    body: EnvironmentRegistrationCallbackBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Environments/{environmentId}/archive',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__environments__environment_id_archive(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Environments/{environmentId}/archive',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__environments__environment_id_archive(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Environments/{environmentId}/export',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__environments__environment_id_export(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/Environments/{environmentId}/folder',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_api_v1__environments__environment_id_folder(
    environment_id: str = Path(..., alias='environmentId'),
    body: CloudEnvironmentFolderBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Environments/{environmentId}/heartbeattoken',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__environments__environment_id_heartbeattoken(
    environment_id: str = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Environments/{environmentId}/notify',
    tags=['environment_routes_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__environments__environment_id_notify(
    environment_id: UUID = Path(..., alias='environmentId'),
    body: NotificationDataBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/Environments/{environmentId}/ports/{port}',
    tags=['environment_ports_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__environments__environment_id_ports__port(
    environment_id: str = Path(..., alias='environmentId'),
    port: conint(ge=1, le=65535) = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/Environments/{environmentId}/ports/{port}',
    tags=['environment_ports_management', 'environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1__environments__environment_id_ports__port(
    environment_id: str = Path(..., alias='environmentId'),
    port: conint(ge=1, le=65535) = ...,
    body: AddForwardedPortSettings = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/Environments/{environmentId}/restore',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_api_v1__environments__environment_id_restore(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/Environments/{environmentId}/secrets',
    tags=['secret_storage_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1__environments__environment_id_secrets(
    environment_id: UUID = Path(..., alias='environmentId'),
    body: UpdateUserSecretsRequestBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Environments/{environmentId}/shutdown',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__environments__environment_id_shutdown(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Environments/{environmentId}/start',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__environments__environment_id_start(
    environment_id: UUID = Path(..., alias='environmentId'),
    access: Optional[bool] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Environments/{environmentId}/state',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__environments__environment_id_state(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Environments/{environmentId}/updates',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__environments__environment_id_updates(
    environment_id: str = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Billing/resend',
    tags=['billing_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__geneva_actions__billing_resend(body: ReplayBillRequestBody):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/GenevaActions/Billing/{environmentId}',
    tags=['environment_management', 'environment_routes_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__geneva_actions__billing__environment_id(
    environment_id: UUID = Path(..., alias='environmentId'),
    start_time: Optional[str] = Query(None, alias='startTime'),
    end_time: Optional[str] = Query(None, alias='endTime'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/GenevaActions/Billing/{environmentId}/state-changes',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_billing_environment_state_changes(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Billing/{environmentId}/state-changes',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_environment_state_change(
    environment_id: UUID = Path(..., alias='environmentId'),
    body: CreateEnvironmentStateChangeBody = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Configuration/{target}',
    tags=['configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__geneva_actions__configuration__target(
    target: str, body: UpdateSystemConfigurationBody = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/GenevaActions/Configuration/{target}/{key}',
    tags=['configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__geneva_actions__configuration__target__key(
    target: str, key: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/GenevaActions/Configuration/{target}/{key}',
    tags=['configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__geneva_actions__configuration__target__key(target: str, key: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/GenevaActions/Environments/{environmentId}',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__geneva_actions__environments__environment_id(
    environment_id: UUID = Path(..., alias='environmentId'),
    deletion_type: Optional[str] = Query(None, alias='deletionType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/GenevaActions/Environments/{environmentId}',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__geneva_actions__environments__environment_id(
    environment_id: str = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/GenevaActions/Environments/{environmentId}/archive',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1__geneva_actions__environments__environment_id_archive(
    environment_id: UUID = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/GenevaActions/Environments/{environmentId}/archived_storage_sas/{targetBlob}',
    tags=['environment_management', 'environment_routes_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_archived_storage_target_blob_for_environment(
    environment_id: str = Path(..., alias='environmentId'),
    target_blob: str = Path(..., alias='targetBlob'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/GenevaActions/Environments/{environmentId}/shutdown',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def shutdown_environment_by_id(environment_id: UUID = Path(..., alias='environmentId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Environments/{environmentId}/upload/running/vm/logs',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def upload_vm_logs_to_environment(
    environment_id: str = Path(..., alias='environmentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Pools/change-resource-deletion-setting',
    tags=['resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def change_resource_deletion_setting(body: ChangeResourceDeletionRequestBody):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Pools/{poolCode}/rotate-pool',
    tags=['pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__geneva_actions__pools__pool_code_rotate_pool(
    pool_code: str = Path(..., alias='poolCode')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Pools/{target}',
    tags=['pool_configuration_management', 'configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__geneva_actions__pools__target(
    target: str, body: PoolConfigRequestBody = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Prebuilds/pools/createorupdatesettings',
    tags=['pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_or_update_pool_settings(body: PoolSettingsBody):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Prebuilds/pools/delete',
    tags=['pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__geneva_actions__prebuilds_pools_delete(body: PoolSettingsBody):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Privacy/refresh-profile-telemetry-properties',
    tags=['profile_telemetry_management', 'telemetry_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def refresh_profile_telemetry_properties(
    body: RefreshProfileTelemetryPropertiesRequest,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/Resources/{resourceId}/under-investigation',
    tags=['resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_resource_investigation_status(resource_id: str = Path(..., alias='resourceId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/GenevaActions/VnetPoolDefinitions',
    tags=['pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__geneva_actions__vnet_pool_definitions(
    body: PoolDefinitionInput = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/GenevaActions/VnetPoolDefinitions',
    tags=['pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__geneva_actions__vnet_pool_definitions(
    body: PoolDefinitionInput = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/HeartBeat',
    tags=['heartbeat_signal_management', 'application_health_check_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__heart_beat(body: HeartBeatBody = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Locations',
    tags=['telemetry_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__locations():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Locations/{location}',
    tags=[
        'location_info_services',
        'plan_resource_operations_management',
        'delegated_access_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__locations__location(
    location: str, plan_id: Optional[str] = Query(None, alias='planId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Prebuilds/pools/{poolId}/instances',
    tags=['environment_management', 'pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__prebuilds_pools__pool_id_instances(
    pool_id: str = Path(..., alias='poolId'),
    body: CreateEnvironmentPoolResourceBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/Prebuilds/pools/{poolId}/instances',
    tags=['environment_management', 'pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1__prebuilds_pools__pool_id_instances(
    pool_id: str = Path(..., alias='poolId'),
    body: CreateEnvironmentPoolResourceBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Prebuilds/template/{environmentId}',
    tags=['environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_template_info_route(environment_id: UUID = Path(..., alias='environmentId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Prebuilds/templates/repo/{repoId}/branch/{branchName}/hash/{prebuildHash}/location/{location}/skus',
    tags=['prebuild_pool_management', 'environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_prebuild_readiness_route(
    repo_id: str = Path(..., alias='repoId'),
    branch_name: str = Path(..., alias='branchName'),
    prebuild_hash: str = Path(..., alias='prebuildHash'),
    location: str = ...,
    storage_type: Optional[StorageType] = Query(None, alias='storageType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Sas',
    tags=['telemetry_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__sas():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Secrets',
    tags=[
        'plan_resource_operations_management',
        'delegated_access_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__secrets(plan_id: Optional[str] = Query(None, alias='planId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Secrets',
    tags=[
        'secret_storage_management',
        'resource_management',
        'plan_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__secrets(
    plan_id: Optional[str] = Query(None, alias='planId'),
    body: ScopedCreateSecretBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/Secrets/{secretId}',
    tags=['secret_storage_management', 'plan_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__secrets__secret_id(
    plan_id: Optional[str] = Query(None, alias='planId'),
    scope: Optional[SecretScope] = None,
    secret_id: UUID = Path(..., alias='secretId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/Secrets/{secretId}',
    tags=['secret_storage_management', 'plan_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1__secrets__secret_id(
    plan_id: Optional[str] = Query(None, alias='planId'),
    secret_id: UUID = Path(..., alias='secretId'),
    body: ScopedUpdateSecretBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/Tenant/{tenantId}',
    tags=['tenant_info_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__tenant__tenant_id(tenant_id: UUID = Path(..., alias='tenantId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Tenant/{tenantId}',
    tags=['tenant_info_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__tenant__tenant_id(tenant_id: UUID = Path(..., alias='tenantId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/Tenant/{tenantId}',
    tags=['tenant_info_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1__tenant__tenant_id(tenant_id: UUID = Path(..., alias='tenantId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/plans/{planName}/deleteAllCodespaces',
    tags=['plan_resource_operations_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__tokens_plans__plan_name_delete_all_codespaces(
    plan_name: str = Path(..., alias='planName'),
    x_subscription_id: Optional[str] = Header(None, alias='x-subscription-id'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/plans/{planName}/readAllCodespaces',
    tags=[
        'delegated_access_operations_management',
        'subscription_operations_management',
        'plan_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__tokens_plans__plan_name_read_all_codespaces(
    plan_name: str = Path(..., alias='planName'),
    x_subscription_id: Optional[str] = Header(None, alias='x-subscription-id'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/plans/{planName}/writeCodespaces',
    tags=['plan_resource_operations_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__tokens_plans__plan_name_write_codespaces(
    plan_name: str = Path(..., alias='planName'),
    x_subscription_id: Optional[str] = Header(None, alias='x-subscription-id'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/plans/{planName}/writeDelegates',
    tags=[
        'delegated_access_operations_management',
        'resource_access_delegation_management',
        'subscription_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__tokens_plans__plan_name_write_delegates(
    plan_name: str = Path(..., alias='planName'),
    x_subscription_id: Optional[str] = Header(None, alias='x-subscription-id'),
    body: IssueDelegatePlanAccessTokenBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}',
    tags=[
        'plan_resource_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_tokens_subscription_resource_plans_by_resource_name(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    headers: Optional[PlanResourceHeaders] = None,
    body: PlanResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}/deleteAllCodespaces',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_all_codespaces_for_subscription_and_resources(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}/deleteAllEnvironments',
    tags=['subscription_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_all_environments_for_subscription_and_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}/readAllCodespaces',
    tags=['subscription_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_all_codespaces_for_subscription_resource_group_provider(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}/readAllEnvironments',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_all_environments_by_subscription_and_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}/writeCodespaces',
    tags=[
        'resource_management',
        'subscription_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def write_codespace_resource_expiration(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}/writeDelegates',
    tags=[
        'delegated_access_operations_management',
        'resource_access_delegation_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def write_issue_delegate_plan_access_token(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    body: IssueDelegatePlanAccessTokenBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/Tokens/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/{providerNamespace}/plans/{resourceName}/writeEnvironments',
    tags=['subscription_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def write_environment_for_resource_plan(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    provider_namespace: str = Path(..., alias='providerNamespace'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Tunnel/{environmentId}/portInfo',
    tags=['environment_ports_management', 'environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1__tunnel__environment_id_port_info(
    environment_id: UUID = Path(..., alias='environmentId'),
    port_number: Optional[int] = Query(None, alias='portNumber'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/UserSubscriptions',
    tags=['profile_telemetry_management', 'tenant_info_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1__user_subscriptions(email: Optional[str] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/UserSubscriptions',
    tags=['profile_telemetry_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1__user_subscriptions(email: Optional[str] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/pools/default',
    tags=['environment_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1_pools_default(
    sku_name: Optional[SkuName] = Query(None, alias='skuName')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/subscriptions/{subscriptionId}/providers/GitHub.Network/{resourceType}/SubscriptionLifeCycleNotification',
    tags=[
        'subscription_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_subscription_notification_body(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_type: str = Path(..., alias='resourceType'),
    body: RPSubscriptionNotification = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/providers/GitHub.Network/{resourceType}/resourceReadBegin',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_subscription_resource_read_begin(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_type: str = Path(..., alias='resourceType'),
    body: NetworkSettingsResourceList = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/subscriptions/{subscriptionId}/providers/Microsoft.Codespaces/plans/SubscriptionLifeCycleNotification',
    tags=[
        'subscription_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_subscription_lifecycle_notification(
    subscription_id: str = Path(..., alias='subscriptionId'),
    body: RPSubscriptionNotification = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/providers/Microsoft.Codespaces/plans/resourceReadBegin',
    tags=[
        'subscription_operations_management',
        'plan_resource_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_microsoft_codespaces_plans_for_subscription(
    subscription_id: str = Path(..., alias='subscriptionId'),
    body: PlanResourceList = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/subscriptions/{subscriptionId}/providers/Microsoft.VSOnline/plans/SubscriptionLifeCycleNotification',
    tags=[
        'subscription_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def handle_subscription_lifecycle_notification(
    subscription_id: str = Path(..., alias='subscriptionId'),
    body: RPSubscriptionNotification = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/providers/Microsoft.VSOnline/plans/resourceReadBegin',
    tags=[
        'subscription_operations_management',
        'plan_resource_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_microsoft_online_subscription_plans(
    subscription_id: str = Path(..., alias='subscriptionId'),
    body: PlanResourceList = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/resourceReadBegin',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_network_settings_resource_list(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    body: NetworkSettingsResourceList = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_network_settings_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
    body: NetworkSettingsResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_network_settings_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
    body: NetworkSettingsResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def configure_network_settings_for_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
    body: NetworkSettingsResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}/resourceCreationCompleted',
    tags=['resource_management', 'subscription_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_resource_completion_notification(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}/resourceCreationValidate',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_network_resource_creation(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
    body: NetworkSettingsResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}/resourceDeletionCompleted',
    tags=['resource_management', 'subscription_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_resource_from_subscription_and_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}/resourceDeletionValidate',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_resource_deletion_network_settings(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
    body: NetworkSettingsResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}/resourcePatchCompleted',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_completed_resource_in_subscription_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}/resourcePatchValidate',
    tags=['network_settings_control_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_network_settings_resource_patch(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
    body: NetworkSettingsResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/GitHub.Network/{resourceType}/{resourceName}/resourceReadBegin',
    tags=['resource_management', 'network_settings_control_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_network_settings_for_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_type: str = Path(..., alias='resourceType'),
    resource_name: str = Path(..., alias='resourceName'),
    body: NetworkSettingsResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/resourceReadBegin',
    tags=[
        'subscription_operations_management',
        'plan_resource_operations_management',
        'resource_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_plan_resource_list_for_subscription_and_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    body: PlanResourceList = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}',
    tags=[
        'resource_management',
        'subscription_resource_operations_management',
        'plan_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_subscription_resource_group_plan_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    headers: Optional[PlanResourceHeaders] = None,
    body: PlanResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/deleteAllCodespaces',
    tags=[
        'subscription_operations_management',
        'resource_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_all_codespaces_from_plan(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/deleteAllEnvironments',
    tags=['subscription_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_all_environments_from_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/readAllCodespaces',
    tags=['subscription_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_all_codespaces_from_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/readAllEnvironments',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_all_environments_for_subscription_and_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/readDelegates',
    tags=['resource_management', 'subscription_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_codespace_plan_resource_details(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/resourceCreationCompleted',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_resource_creation_completed_info(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/resourceCreationValidate',
    tags=[
        'resource_management',
        'subscription_operations_management',
        'plan_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_plan_resource_creation(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: PlanResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/resourceDeletionValidate',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_codespace_plan_resource_deletion(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/resourcePatchCompleted',
    tags=[
        'plan_resource_operations_management',
        'resource_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_subscription_resource_plan(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    headers: Optional[PlanResourceHeaders] = None,
    body: PlanResourceUpdateBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/resourcePatchValidate',
    tags=[
        'plan_resource_operations_management',
        'resource_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_plan_resource_update(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: PlanResourceUpdateBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/resourceReadBegin',
    tags=[
        'resource_management',
        'plan_resource_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_plan_resource_by_subscription_and_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: PlanResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/writeCodespaces',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def write_codespace_plan_resource_group_subscription(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/writeDelegates',
    tags=[
        'delegated_access_operations_management',
        'resource_access_delegation_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def write_delegate_plan_access_token(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: IssueDelegatePlanAccessTokenBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/writeEnvironments',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_environment_for_subscription_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/resourceReadBegin',
    tags=[
        'subscription_operations_management',
        'plan_resource_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_vso_plans_from_subscription_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    body: PlanResourceList = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}',
    tags=[
        'resource_management',
        'plan_resource_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_subscription_resource_group_plan_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    headers: Optional[PlanResourceHeaders] = None,
    body: PlanResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/deleteAllCodespaces',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_all_codespaces_expired_by_subscription_and_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/deleteAllEnvironments',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_all_environments_from_subscription_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/readAllCodespaces',
    tags=[
        'resource_management',
        'subscription_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_all_codespaces_for_subscription_and_resource(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/readAllEnvironments',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_all_resource_environments_for_subscription_and_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/readDelegates',
    tags=['resource_management', 'subscription_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def read_resource_plan_delegates(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/resourceCreationCompleted',
    tags=[
        'resource_management',
        'subscription_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_resource_completion_info(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/resourceCreationValidate',
    tags=[
        'resource_management',
        'subscription_operations_management',
        'plan_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_resource_creation_plan(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: PlanResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/resourceDeletionValidate',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_resource_deletion_for_subscription(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/resourcePatchCompleted',
    tags=[
        'resource_management',
        'subscription_resource_operations_management',
        'plan_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_plan_resource_patch_completed(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    headers: Optional[PlanResourceHeaders] = None,
    body: PlanResourceUpdateBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/resourcePatchValidate',
    tags=[
        'plan_resource_operations_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def validate_plan_resource_update_patch(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: PlanResourceUpdateBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/resourceReadBegin',
    tags=[
        'subscription_resource_operations_management',
        'plan_resource_operations_management',
        'resource_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_plan_resource_for_subscription(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: PlanResource = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/writeCodespaces',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def write_resource_expiration_codespace(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/writeDelegates',
    tags=[
        'delegated_access_operations_management',
        'resource_access_delegation_management',
        'subscription_resource_operations_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_issue_delegate_plan_access_token(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    body: IssueDelegatePlanAccessTokenBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/writeEnvironments',
    tags=['resource_management', 'subscription_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def write_environment_for_subscription_resource_group(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
    expiration: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/{resourceGroup}/providers/Microsoft.Codespaces/plans/{resourceName}/deleteDelegates',
    tags=['resource_management', 'subscription_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_codespace_plan_delegate(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/subscriptions/{subscriptionId}/{resourceGroup}/providers/Microsoft.VSOnline/plans/{resourceName}/deleteDelegates',
    tags=['resource_management', 'subscription_resource_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_vso_plan_resource_delegate(
    subscription_id: str = Path(..., alias='subscriptionId'),
    resource_group: str = Path(..., alias='resourceGroup'),
    resource_name: str = Path(..., alias='resourceName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/tenant/{tenantId}/Pool/{poolName}',
    tags=['tenant_pool_operations_management', 'pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1_tenant__tenant_id__pool__pool_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/tenant/{tenantId}/Pool/{poolName}',
    tags=['pool_configuration_management', 'tenant_pool_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1_tenant__tenant_id__pool__pool_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/tenant/{tenantId}/Pool/{poolName}',
    tags=['pool_configuration_management', 'tenant_pool_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_api_v1_tenant__tenant_id__pool__pool_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
    body: CreateOrUpdatePoolBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/tenant/{tenantId}/Pool/{poolName}',
    tags=['pool_configuration_management', 'tenant_pool_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1_tenant__tenant_id__pool__pool_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
    body: CreateOrUpdatePoolBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/tenant/{tenantId}/PoolGroup/{poolGroupName}',
    tags=['tenant_pool_operations_management', 'pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1_tenant__tenant_id__pool_group__pool_group_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_group_name: str = Path(..., alias='poolGroupName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/tenant/{tenantId}/PoolGroup/{poolGroupName}',
    tags=['tenant_pool_operations_management', 'pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1_tenant__tenant_id__pool_group__pool_group_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_group_name: str = Path(..., alias='poolGroupName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/tenant/{tenantId}/PoolGroup/{poolGroupName}',
    tags=[
        'tenant_pool_operations_management',
        'pool_configuration_management',
        'tenant_info_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_api_v1_tenant__tenant_id__pool_group__pool_group_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_group_name: str = Path(..., alias='poolGroupName'),
    body: UpdatePoolGroupBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/tenant/{tenantId}/PoolGroup/{poolGroupName}',
    tags=['tenant_pool_operations_management', 'pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1_tenant__tenant_id__pool_group__pool_group_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_group_name: str = Path(..., alias='poolGroupName'),
    body: CreatePoolGroupBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/tenant/{tenantId}/pool/{poolName}/Vm',
    tags=['tenant_pool_operations_management', 'pool_configuration_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1_tenant__tenant_id_pool__pool_name__vm(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/tenant/{tenantId}/pool/{poolName}/Vm/{vmName}',
    tags=['tenant_pool_operations_management', 'environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v1_tenant__tenant_id_pool__pool_name__vm__vm_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
    vm_name: str = Path(..., alias='vmName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/tenant/{tenantId}/pool/{poolName}/Vm/{vmName}',
    tags=['tenant_pool_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_api_v1_tenant__tenant_id_pool__pool_name__vm__vm_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
    vm_name: str = Path(..., alias='vmName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/tenant/{tenantId}/pool/{poolName}/Vm/{vmName}',
    tags=['tenant_pool_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def put_api_v1_tenant__tenant_id_pool__pool_name__vm__vm_name(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
    vm_name: str = Path(..., alias='vmName'),
    body: ClaimVMBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/tenant/{tenantId}/pool/{poolName}/Vm/{vmName}/start',
    tags=['tenant_pool_operations_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1_tenant__tenant_id_pool__pool_name__vm__vm_name_start(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
    vm_name: str = Path(..., alias='vmName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/tenant/{tenantId}/pool/{poolName}/Vm/{vmName}/stop',
    tags=['tenant_pool_operations_management', 'environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v1_tenant__tenant_id_pool__pool_name__vm__vm_name_stop(
    tenant_id: UUID = Path(..., alias='tenantId'),
    pool_name: str = Path(..., alias='poolName'),
    vm_name: str = Path(..., alias='vmName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v2/prebuilds/delete',
    tags=['prebuild_template_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v2_prebuilds_delete(body: DeletePrebuildTemplatesBody = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v2/prebuilds/repository/{repoId}/branch/{branchName}',
    tags=['environment_management', 'resource_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_api_v2_prebuilds_repository__repo_id_branch__branch_name(
    repo_id: int = Path(..., alias='repoId'),
    branch_name: str = Path(..., alias='branchName'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v2/prebuilds/templates',
    tags=['prebuild_template_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v2_prebuilds_templates(body: CreatePrebuildTemplateBody = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v2/prebuilds/templates/skus/repo/{repoId}/branch/{branchName}/hash/{prebuildHash}/location/{location}/devcontainerpath/{devContainerPath}',
    tags=[
        'environment_management',
        'prebuild_pool_management',
        'codespace_configuration_management',
        'resource_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_prebuild_readiness_skus_route(
    repo_id: str = Path(..., alias='repoId'),
    branch_name: str = Path(..., alias='branchName'),
    prebuild_hash: str = Path(..., alias='prebuildHash'),
    location: str = ...,
    dev_container_path: str = Path(..., alias='devContainerPath'),
    storage_type: Optional[StorageType] = Query(None, alias='storageType'),
    fast_path_enabled: Optional[bool] = Query(None, alias='fastPathEnabled'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v2/prebuilds/templates/updatemaxversions',
    tags=['prebuild_template_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v2_prebuilds_templates_updatemaxversions(
    body: UpdatePrebuildTemplateVersionsBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v2/prebuilds/templates/{templateId}/updatestatus',
    tags=['prebuild_template_operations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_api_v2_prebuilds_templates__template_id_updatestatus(
    template_id: UUID = Path(..., alias='templateId'),
    body: UpdatePrebuildTemplateBody = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/health',
    tags=['application_health_check_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_health():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/internal/Netmon/correlation',
    tags=['telemetry_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_internal__netmon_correlation(
    mac_address: Optional[str] = Query(None, alias='macAddress')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/tunnelauth',
    tags=['environment_ports_management', 'environment_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_tunnelauth(
    id: Optional[str] = None,
    cluster: Optional[str] = None,
    name: Optional[str] = None,
    port: Optional[int] = None,
    pb: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/tunnelauth',
    tags=['environment_ports_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_tunnelauth(
    op: Optional[str] = None,
    id: Optional[str] = None,
    cluster: Optional[str] = None,
    name: Optional[str] = None,
    port: Optional[int] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/warmup',
    tags=['telemetry_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_warmup():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
