# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:43:19+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, RootModel, constr


class AgentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assetUri: Optional[str] = None
    family: Optional[str] = None
    name: Optional[str] = None


class AvailableSettingsResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sku: Optional[List[str]] = None


class AzureLocation(Enum):
    field_101__EastAsia_ = '101 (EastAsia)'
    field_102__SouthEastAsia_ = '102 (SouthEastAsia)'
    field_201__AustraliaCentral_ = '201 (AustraliaCentral)'
    field_202__AustraliaCentral2_ = '202 (AustraliaCentral2)'
    field_203__AustraliaEast_ = '203 (AustraliaEast)'
    field_205__AustraliaSouthEast_ = '205 (AustraliaSouthEast)'
    field_301__BrazilSouth_ = '301 (BrazilSouth)'
    field_401__CanadaCentral_ = '401 (CanadaCentral)'
    field_402__CanadaEast_ = '402 (CanadaEast)'
    field_501__NorthEurope_ = '501 (NorthEurope)'
    field_502__WestEurope_ = '502 (WestEurope)'
    field_601__FranceCentral_ = '601 (FranceCentral)'
    field_602__FranceSouth_ = '602 (FranceSouth)'
    field_701__CentralIndia_ = '701 (CentralIndia)'
    field_702__SouthIndia_ = '702 (SouthIndia)'
    field_703__WestIndia_ = '703 (WestIndia)'
    field_801__JapanEast_ = '801 (JapanEast)'
    field_802__JapanWest_ = '802 (JapanWest)'
    field_901__KoreaCentral_ = '901 (KoreaCentral)'
    field_902__KoreaSouth_ = '902 (KoreaSouth)'
    field_1001__SouthAfricaNorth_ = '1001 (SouthAfricaNorth)'
    field_1002__SouthAfricaWest_ = '1002 (SouthAfricaWest)'
    field_1201__UaeCentral_ = '1201 (UaeCentral)'
    field_1202__UaeNorth_ = '1202 (UaeNorth)'
    field_1401__UkSouth_ = '1401 (UkSouth)'
    field_1402__UkWest_ = '1402 (UkWest)'
    field_1501__CentralUs_ = '1501 (CentralUs)'
    field_1502__EastUs_ = '1502 (EastUs)'
    field_1503__EastUs2_ = '1503 (EastUs2)'
    field_1504__NorthCentralUs_ = '1504 (NorthCentralUs)'
    field_1505__SouthCentralUs_ = '1505 (SouthCentralUs)'
    field_1506__WestCentralUs_ = '1506 (WestCentralUs)'
    field_1507__WestUs_ = '1507 (WestUs)'
    field_1508__WestUs2_ = '1508 (WestUs2)'
    field_1509__WestUs3_ = '1509 (WestUs3)'
    field_1601__CentralUsEuap_ = '1601 (CentralUsEuap)'
    field_1602__EastUs2Euap_ = '1602 (EastUs2Euap)'
    field_1701__SwitzerlandNorth_ = '1701 (SwitzerlandNorth)'
    field_1702__SwitzerlandWest_ = '1702 (SwitzerlandWest)'
    field_1801__GermanyNorth_ = '1801 (GermanyNorth)'
    field_1802__GermanyWestCentral_ = '1802 (GermanyWestCentral)'
    field_1901__NorwayWest_ = '1901 (NorwayWest)'
    field_1902__NorwayEast_ = '1902 (NorwayEast)'


class BillableOwnerType(Enum):
    field_0__User_ = '0 (User)'
    field_1__Organization_ = '1 (Organization)'


class BillingProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    billingType: Optional[str] = None
    channelType: Optional[str] = None
    paymentType: Optional[str] = None
    tier: Optional[str] = None
    workloadType: Optional[str] = None


class ChangeResourceDeletionRequestBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comment: Optional[str] = None
    enabled: Optional[bool] = None
    poolCode: Optional[str] = None
    poolType: Optional[str] = None
    region: Optional[str] = None


class ClientUsageData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeMinutes: Optional[int] = None
    lastActivity: Optional[datetime] = None


class ClientUsageSession(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sessionId: Optional[str] = None
    usageData: Optional[Dict[str, ClientUsageData]] = None


class CloudEnvironmentFolderBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    recentFolderPaths: Optional[List[str]] = None


class CloudEnvironmentState(Enum):
    field_0__None_ = '0 (None)'
    field_1__Created_ = '1 (Created)'
    field_2__Queued_ = '2 (Queued)'
    field_3__Provisioning_ = '3 (Provisioning)'
    field_4__Available_ = '4 (Available)'
    field_5__Awaiting_ = '5 (Awaiting)'
    field_6__Unavailable_ = '6 (Unavailable)'
    field_7__Deleted_ = '7 (Deleted)'
    field_8__Moved_ = '8 (Moved)'
    field_9__Shutdown_ = '9 (Shutdown)'
    field_10__Archived_ = '10 (Archived)'
    field_11__Starting_ = '11 (Starting)'
    field_12__ShuttingDown_ = '12 (ShuttingDown)'
    field_13__Failed_ = '13 (Failed)'
    field_14__Exporting_ = '14 (Exporting)'
    field_15__Updating_ = '15 (Updating)'
    field_16__Rebuilding_ = '16 (Rebuilding)'


class CollectedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environmentId: Optional[str] = None
    name: Optional[str] = None
    parentActivityId: Optional[str] = None
    timestamp: Optional[datetime] = None


class ComputeUsageDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sku: Optional[str] = None
    usage: Optional[float] = None


class ConsumerType(Enum):
    field_0__None_ = '0 (None)'
    field_1__System_ = '1 (System)'
    field_2__Trusted_ = '2 (Trusted)'
    field_4__Neutral_ = '4 (Neutral)'
    field_8__Untrusted_ = '8 (Untrusted)'
    field_9__Test_ = '9 (Test)'


class ContainerInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    imageName: Optional[str] = None
    schemaVersion: Optional[str] = None


class ContainerInfoBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    schemaVersion: Optional[str] = None


class CreateEnvironmentStateChangeBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    newValue: Optional[CloudEnvironmentState] = None
    oldValue: Optional[CloudEnvironmentState] = None
    time: Optional[datetime] = None


class CreatePoolGroupBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: str
    region: AzureLocation
    tags: Optional[Dict[str, str]] = None


class CreateTemplateResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    properties: Optional[Dict[str, str]] = None
    sasUrl: Optional[str] = None
    templateId: Optional[str] = None


class DelegateIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: Optional[str] = None
    id: Optional[str] = None
    username: Optional[str] = None


class DeletePrebuildTemplatesBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branchName: str
    devContainerPath: Optional[str] = None
    prebuildConfigurationId: Optional[int] = None
    repoId: int


class DomainUserCredentials(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domain: str
    organizationalUnit: Optional[str] = None
    passwordSecretIdentifier: str
    userName: str


class EnvironmentRegistrationCallbackPayloadBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sessionId: Optional[str] = None
    sessionPath: Optional[str] = None


class ExperimentalFeaturesBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enableDynamicHttpsDetection: Optional[bool] = None
    queueResourceAllocation: Optional[bool] = None
    usePrebuildFastPathIfAvailable: Optional[bool] = None
    usePrebuiltImages: Optional[bool] = None
    useStorageV2: Optional[bool] = None


class FailoverDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failoverEnabled: Optional[bool] = None
    failoverRegion: Optional[AzureLocation] = None


class GitConfigOptionsBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    userEmail: Optional[str] = None
    userName: Optional[str] = None


class GitStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ahead: Optional[int] = None
    behind: Optional[int] = None
    branch: Optional[str] = None
    commit: Optional[str] = None
    hasUncommittedChanges: Optional[bool] = None
    hasUnpushedChanges: Optional[bool] = None
    noGitRepo: Optional[bool] = None


class HeartBeatBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentVersion: Optional[str] = None
    collectedDataList: Optional[List[CollectedData]] = None
    environmentId: Optional[str] = None
    resourceId: Optional[UUID] = None
    timeStamp: Optional[datetime] = None


class HotPoolSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    size: Optional[int] = None


class IdentityBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: Optional[str] = None
    id: Optional[str] = None
    userName: Optional[str] = None


class IssueDelegatePlanAccessTokenBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environmentIds: Optional[List[str]] = None
    expiration: Optional[datetime] = None
    identity: Optional[DelegateIdentity] = None
    portNumbers: Optional[List[int]] = None
    scope: Optional[str] = None


class LocationsResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: Optional[List[AzureLocation]] = None
    current: Optional[AzureLocation] = None
    hostnames: Optional[Dict[str, str]] = None


class MessageCodes(Enum):
    field_0__Unknown_ = '0 (Unknown)'
    field_1__ExceededQuota_ = '1 (ExceededQuota)'
    field_2__EnvironmentNameAlreadyExists_ = '2 (EnvironmentNameAlreadyExists)'
    field_3__EnvironmentDoesNotExist_ = '3 (EnvironmentDoesNotExist)'
    field_4__ShutdownStaticEnvironment_ = '4 (ShutdownStaticEnvironment)'
    field_5__StartStaticEnvironment_ = '5 (StartStaticEnvironment)'
    field_6__EnvironmentNotAvailable_ = '6 (EnvironmentNotAvailable)'
    field_7__EnvironmentNotShutdown_ = '7 (EnvironmentNotShutdown)'
    field_8__UnableToAllocateResources_ = '8 (UnableToAllocateResources)'
    field_9__UnableToAllocateResourcesWhileStarting_ = (
        '9 (UnableToAllocateResourcesWhileStarting)'
    )
    field_10__RequestedAutoShutdownDelayMinutesIsInvalid_ = (
        '10 (RequestedAutoShutdownDelayMinutesIsInvalid)'
    )
    field_11__UnableToUpdateSku_ = '11 (UnableToUpdateSku)'
    field_12__RequestedSkuIsInvalid_ = '12 (RequestedSkuIsInvalid)'
    field_13__HeartbeatUnhealthy_ = '13 (HeartbeatUnhealthy)'
    field_14__StartEnvironmentGenericError_ = '14 (StartEnvironmentGenericError)'
    field_15__RestoringFromArchive_ = '15 (RestoringFromArchive)'
    field_16__FilePathIsInvalid_ = '16 (FilePathIsInvalid)'
    field_17__TooManyRecentFolders_ = '17 (TooManyRecentFolders)'
    field_18__SubscriptionIsBanned_ = '18 (SubscriptionIsBanned)'
    field_19__EnvironmentArchived_ = '19 (EnvironmentArchived)'
    field_20__SubscriptionStateIsNotRegistered_ = (
        '20 (SubscriptionStateIsNotRegistered)'
    )
    field_21__FeatureDisabled_ = '21 (FeatureDisabled)'
    field_22__SubscriptionCannotPerformAction_ = '22 (SubscriptionCannotPerformAction)'
    field_23__InvalidLocationChange_ = '23 (InvalidLocationChange)'
    field_24__PlanDoesNotExist_ = '24 (PlanDoesNotExist)'
    field_25__UnableToResolveEnvironmentNameConflict_ = (
        '25 (UnableToResolveEnvironmentNameConflict)'
    )
    field_26__ExceededSecretsQuota_ = '26 (ExceededSecretsQuota)'
    field_27__InvalidPlanTenant_ = '27 (InvalidPlanTenant)'
    field_28__ExportStaticEnvironment_ = '28 (ExportStaticEnvironment)'
    field_29__ExportEnvironmentGenericError_ = '29 (ExportEnvironmentGenericError)'
    field_30__ExceededOrgDevContainerMaxLength_ = (
        '30 (ExceededOrgDevContainerMaxLength)'
    )
    field_31__ActionNotAllowedInThisState_ = '31 (ActionNotAllowedInThisState)'
    field_32__ExportRunningEnvironmentError_ = '32 (ExportRunningEnvironmentError)'
    field_34__EnvironmentCreationIsNotAllowed_ = '34 (EnvironmentCreationIsNotAllowed)'
    field_35__GitHubProxyError_ = '35 (GitHubProxyError)'
    field_36__PrebuildTemplateDeletionIsNotAllowed_ = (
        '36 (PrebuildTemplateDeletionIsNotAllowed)'
    )
    field_37__TierCapacityIsUnavailable_ = '37 (TierCapacityIsUnavailable)'


class NetmonCorrelationDataBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    billableOwnerCreatedAt: Optional[str] = None
    billableOwnerDatabaseId: Optional[str] = None
    billableOwnerGlobalRelayId: Optional[str] = None
    billableOwnerPlan: Optional[str] = None
    ownerCreatedAt: Optional[str] = None
    ownerDatabaseId: Optional[str] = None
    ownerGlobalRelayId: Optional[str] = None
    ownerPlan: Optional[str] = None
    repositoryCreatedAt: Optional[str] = None
    repositoryDatabaseId: Optional[str] = None
    repositoryGlobalRelayId: Optional[str] = None
    repositoryPrivate: Optional[bool] = None


class NetworkSettingsResourceProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subnetId: Optional[str] = None


class NotificationDataBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    details: Optional[str] = None
    displayMode: Optional[str] = None
    message: Optional[str] = None
    modal: Optional[bool] = None


class PersonalizationInfoBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dotfilesInstallCommand: Optional[str] = None
    dotfilesRepository: Optional[str] = None
    dotfilesTargetPath: Optional[str] = None


class PlanResourceHeaders(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clientTenantId: Optional[UUID] = None
    homeTenantId: Optional[UUID] = None
    identityPrincipalId: Optional[UUID] = None
    identityUrl: Optional[str] = None


class PlanResourceIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    principalId: Optional[UUID] = None
    tenantId: Optional[UUID] = None
    type: Optional[str] = None


class PlanResourceKeyVaultProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyName: Optional[str] = None
    keyVaultUri: Optional[str] = None
    keyVersion: Optional[str] = None


class PoolConfigRequestBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comment: Optional[str] = None
    maxTargetCount: Optional[str] = None
    minTargetCount: Optional[str] = None
    poolCode: Optional[str] = None
    poolType: Optional[str] = None
    region: Optional[str] = None
    targetCount: Optional[str] = None


class PoolGroupResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: Optional[str] = None
    region: Optional[AzureLocation] = None
    tags: Optional[Dict[str, str]] = None


class PoolStatusResponseBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allWithLatestVersion: Optional[bool] = None
    isEnvironmentPool: Optional[bool] = None
    location: Optional[str] = None
    poolCode: Optional[str] = None
    readyUnassignedCount: Optional[int] = None
    readyUnassignedLatestVersionCount: Optional[int] = None
    readyUnassignedNotLatestVersionAndIdleCount: Optional[int] = None
    readyUnassignedNotLatestVersionCount: Optional[int] = None
    resourceType: Optional[str] = None
    sku: Optional[str] = None


class PrebuildEnvironmentOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    correlationId: Optional[str] = None


class PrebuildMode(Enum):
    field_0__None_ = '0 (None)'
    field_1__Blob_ = '1 (Blob)'
    field_2__CodespacePool_ = '2 (CodespacePool)'
    field_3__StoragePool_ = '3 (StoragePool)'
    field_4__CodespaceAndStoragePool_ = '4 (CodespaceAndStoragePool)'


class PrebuildReadinessResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branchName: Optional[str] = None
    devContainerPath: Optional[str] = None
    location: Optional[AzureLocation] = None
    poolSkus: Optional[List[str]] = None
    prebuildHash: Optional[str] = None
    repoId: Optional[str] = None
    supportedSkus: Optional[List[str]] = None
    templateSkus: Optional[List[str]] = None


class PrebuildTemplateInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    container: Optional[ContainerInfo] = None
    prebuildConfigurationId: Optional[str] = None
    templateSizeInGB: Optional[float] = None
    totalTimeSavingsInSeconds: Optional[str] = None
    workFlowRunId: Optional[str] = None


class PrebuildTemplateInfoResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branchName: Optional[str] = None
    commitId: Optional[str] = None
    id: Optional[str] = None
    isPrebuild: Optional[bool] = None
    lastUsedTime: Optional[datetime] = None
    logicalSkus: Optional[List[str]] = None
    prebuildHash: Optional[str] = None
    repoId: Optional[int] = None
    templateStatus: Optional[str] = None


class PrivacyEnum(Enum):
    field_0__Private_ = '0 (Private)'
    field_1__Public_ = '1 (Public)'
    field_2__Org_ = '2 (Org)'


class ProblemDetails(BaseModel):
    detail: Optional[str] = None
    instance: Optional[str] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class ProfileSpecifier(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oid: Optional[str] = None
    provider: Optional[str] = None
    tid: Optional[str] = None


class ProvisioningStatusResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completedSteps: Optional[int] = None
    currentStepDescription: Optional[str] = None
    isReady: Optional[bool] = None
    operationStartedTimeUtc: Optional[str] = None
    totalSteps: Optional[int] = None


class RefreshProfileTelemetryPropertiesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    partner: Optional[str] = None
    tenantId: Optional[str] = None
    userIds: Optional[str] = None


class RefreshProfileTelemetryPropertiesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failed: Optional[List[ProfileSpecifier]] = None
    succeeded: Optional[List[ProfileSpecifier]] = None


class ReplayBillRequestBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    endTime: Optional[datetime] = None
    startTime: Optional[datetime] = None


class RepositoryInfoBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branchName: Optional[str] = None
    commitId: Optional[str] = None
    createType: Optional[str] = None
    diskUsage: Optional[str] = None
    name: Optional[str] = None
    owner: Optional[str] = None
    prebuildHash: Optional[str] = None
    repoId: Optional[int] = None
    url: Optional[str] = None


class ResourceSubtype(Enum):
    field_0__Default_ = '0 (Default)'
    field_2__ShrunkBlob_ = '2 (ShrunkBlob)'
    field_3__FullBlob_ = '3 (FullBlob)'
    field_4__UserParametersBlob_ = '4 (UserParametersBlob)'
    field_5__PrebuildHash_ = '5 (PrebuildHash)'
    field_6__VnetInjected_ = '6 (VnetInjected)'


class ResourceType(Enum):
    field_1__ComputeVM_ = '1 (ComputeVM)'
    field_2__StorageFileShare_ = '2 (StorageFileShare)'
    field_3__StorageArchive_ = '3 (StorageArchive)'
    field_4__KeyVault_ = '4 (KeyVault)'
    field_5__OSDisk_ = '5 (OSDisk)'
    field_6__NetworkInterface_ = '6 (NetworkInterface)'
    field_7__InputQueue_ = '7 (InputQueue)'
    field_8__Snapshot_ = '8 (Snapshot)'
    field_9__PoolQueue_ = '9 (PoolQueue)'
    field_10__VirtualNetwork_ = '10 (VirtualNetwork)'
    field_11__NetworkSecurityGroup_ = '11 (NetworkSecurityGroup)'
    field_12__LiveShareWorkspace_ = '12 (LiveShareWorkspace)'
    field_13__BasisTunnel_ = '13 (BasisTunnel)'
    field_14__StorageBlockBlob_ = '14 (StorageBlockBlob)'
    field_15__DataDisk_ = '15 (DataDisk)'
    field_16__PortForwardingWorkspace_ = '16 (PortForwardingWorkspace)'


class RuntimeConstraintsBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowedPortPrivacySettings: Optional[List[PrivacyEnum]] = None
    imageAllowList: Optional[List[str]] = None


class SecretFilterType(Enum):
    field_1__GitRepo_ = '1 (GitRepo)'
    field_2__CodespaceName_ = '2 (CodespaceName)'


class SecretScope(Enum):
    field_1__Plan_ = '1 (Plan)'
    field_2__User_ = '2 (User)'


class SecretType(Enum):
    field_1__EnvironmentVariable_ = '1 (EnvironmentVariable)'
    field_2__ContainerRegistry_ = '2 (ContainerRegistry)'


class SeedInfoBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cloneUrl: Optional[str] = None
    gitConfig: Optional[GitConfigOptionsBody] = None
    recurseClone: Optional[bool] = None
    repository: Optional[RepositoryInfoBody] = None
    seedMoniker: Optional[str] = None
    seedType: Optional[str] = None


class Sku(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    tier: Optional[str] = None


class SkuInfoResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availableSettings: Optional[AvailableSettingsResult] = None
    displayName: Optional[str] = None
    name: Optional[str] = None
    os: Optional[str] = None


class StorageType(Enum):
    field_0__V1_ = '0 (V1)'
    field_1__V2_ = '1 (V2)'


class StorageUsageDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    size: Optional[int] = None
    sizeInKB: Optional[int] = None
    sku: Optional[str] = None
    usage: Optional[float] = None


class StringStringKeyValuePair(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Optional[str] = None
    value: Optional[str] = None


class SubscriptionAccountOwner(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Optional[str] = None
    puid: Optional[str] = None


class SubscriptionAdditionalProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    billingProperties: Optional[BillingProperties] = None
    resourceProviderProperties: Optional[str] = None


class SubscriptionData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    computeQuota: Optional[int] = None
    computeUsage: Optional[int] = None
    subscriptionId: Optional[str] = None
    subscriptionState: Optional[str] = None


class SystemConfigurationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comment: Optional[str] = None
    key: Optional[str] = None
    value: Optional[str] = None


class TelemetryData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: Optional[str] = None
    message: Optional[str] = None
    optionalValues: Optional[Dict[str, str]] = None
    time: Optional[str] = None


class TenantInfoResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[UUID] = None


class TunnelPortInfoResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    portVisibility: Optional[str] = None
    tunnelToken: Optional[str] = None


class TunnelProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clusterId: Optional[str] = None
    connectAccessToken: Optional[str] = None
    domain: Optional[str] = None
    managePortsAccessToken: Optional[str] = None
    serviceUri: Optional[str] = None
    tunnelId: Optional[str] = None
    tunnelName: Optional[str] = None


class TunnelType(Enum):
    field_0__Basis_ = '0 (Basis)'
    field_1__Liveshare_ = '1 (Liveshare)'


class UnderInvestigationResponseBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    investigationStarted: Optional[datetime] = None
    resourceId: Optional[str] = None
    underInvestigation: Optional[bool] = None
    updated: Optional[bool] = None


class UpdateCloudEnvironmentBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    autoShutdownDelayMinutes: Optional[int] = None
    failoverDetails: Optional[FailoverDetails] = None
    friendlyName: Optional[str] = None
    planAccessToken: Optional[str] = None
    planId: Optional[str] = None
    skuName: Optional[str] = None


class UpdatePoolGroupBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: str
    tags: Optional[Dict[str, str]] = None


class UpdatePrebuildTemplateBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isSuccess: bool


class UpdatePrebuildTemplateVersionsBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branchName: str
    devContainerPath: Optional[str] = None
    maxPrebuildTemplateVersions: int
    repoId: int


class UpdateSystemConfigurationBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comment: Optional[str] = None
    key: Optional[str] = None
    value: Optional[str] = None


class UserIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    userPrincipalName: str


class VMConnectionType(Enum):
    field_0__LiveShare_ = '0 (LiveShare)'
    field_1__WVD_ = '1 (WVD)'


class VMDiskType(Enum):
    field_0__StandardHDD_ = '0 (StandardHDD)'
    field_1__StandardSSD_ = '1 (StandardSSD)'
    field_2__PremiumSSD_ = '2 (PremiumSSD)'


class VMSpecs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    diskType: VMDiskType
    imageResourceId: str
    size: str
    subnetResourceId: str


class VMStatus(Enum):
    field_0__Provisioning_ = '0 (Provisioning)'
    field_1__Ready_ = '1 (Ready)'
    field_2__Stopped_ = '2 (Stopped)'
    field_3__Deleted_ = '3 (Deleted)'


class VmLogsUploadInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    containerName: Optional[str] = None
    message: Optional[str] = None
    pathInContainer: Optional[str] = None
    storageUri: Optional[str] = None
    vmResourceId: Optional[str] = None


class VnetProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subnetId: Optional[str] = None


class VsoPlanInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    location: Optional[AzureLocation] = None
    name: Optional[str] = None
    providerNamespace: Optional[str] = None
    resourceGroup: Optional[str] = None
    resourceId: Optional[str] = None
    subscription: Optional[str] = None


class ApiV1AgentTelemetryPostRequest(RootModel[List[TelemetryData]]):
    root: List[TelemetryData]


class ApiV1AgentTelemetryStandalonePostRequest(RootModel[List[TelemetryData]]):
    root: List[TelemetryData]


class ApiV1EnvironmentsEnvironmentIdPatchResponse(RootModel[List[MessageCodes]]):
    root: List[MessageCodes]


class ApiV1EnvironmentsEnvironmentIdFolderPatchResponse(RootModel[List[MessageCodes]]):
    root: List[MessageCodes]


class ApiV1PoolsDefaultGetResponse(RootModel[List[PoolStatusResponseBody]]):
    root: List[PoolStatusResponseBody]


class SkuName(RootModel[List[str]]):
    root: List[str]


class AddForwardedPortSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    privacy: Optional[PrivacyEnum] = None
    tunnelType: Optional[TunnelType] = None


class BillableOwnerBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    login: Optional[str] = None
    type: Optional[BillableOwnerType] = None


class ClaimVMBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user: UserIdentity


class ConnectionInfoBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectionServiceUri: Optional[str] = None
    connectionSessionId: Optional[str] = None
    connectionSessionPath: Optional[str] = None
    hostPublicKeys: Optional[List[str]] = None
    relayEndpoint: Optional[str] = None
    relaySasToken: Optional[str] = None
    sessionToken: Optional[str] = None
    tunnelProperties: Optional[TunnelProperties] = None


class CreateOrUpdatePoolBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domainUserCredentials: Optional[DomainUserCredentials] = None
    hotPoolSettings: Optional[HotPoolSettings] = None
    poolGroupName: str
    tags: Optional[Dict[str, str]] = None
    userGroupName: Optional[str] = None
    vmSpecs: VMSpecs


class CreatePrebuildTemplateBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    devContainerPath: Optional[str] = None
    experimentalFeatures: Optional[ExperimentalFeaturesBody] = None
    features: Optional[Dict[str, str]] = None
    friendlyName: str
    planId: Optional[str] = None
    seed: Optional[SeedInfoBody] = None
    storageType: Optional[StorageType] = None
    templateInfo: Optional[PrebuildTemplateInfo] = None


class EnvironmentBillingInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    name: Optional[str] = None
    sku: Optional[Sku] = None
    userId: Optional[str] = None


class EnvironmentRegistrationCallbackBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payload: Optional[EnvironmentRegistrationCallbackPayloadBody] = None
    type: str


class EnvironmentStateChange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environment: Optional[EnvironmentBillingInfo] = None
    id: Optional[str] = None
    newValue: Optional[CloudEnvironmentState] = None
    oldValue: Optional[CloudEnvironmentState] = None
    partitionKey: Optional[str] = None
    time: Optional[datetime] = None


class LocationInfoResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    skus: Optional[List[SkuInfoResult]] = None


class NetworkSettingsResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    location: Optional[str] = None
    name: Optional[str] = None
    properties: Optional[NetworkSettingsResourceProperties] = None
    provisioningState: Optional[str] = None
    tags: Optional[Dict[str, str]] = None
    type: Optional[str] = None


class NetworkSettingsResourceList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Optional[List[NetworkSettingsResource]] = None


class PlanResourceEncryptionProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keySource: Optional[str] = None
    keyVaultProperties: Optional[PlanResourceKeyVaultProperties] = None


class PlanResourceProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defaultCodespaceSku: Optional[str] = None
    defaultEnvironmentSku: Optional[str] = None
    encryption: Optional[PlanResourceEncryptionProperties] = None
    userId: Optional[str] = None
    vnetProperties: Optional[VnetProperties] = None


class PlanResourceUpdateBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identity: Optional[PlanResourceIdentity] = None
    properties: Optional[PlanResourceProperties] = None


class Pool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poolType: Optional[PrebuildMode] = None
    skuName: Optional[str] = None
    targetCount: Optional[int] = None


class PoolDefinitionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dimensions: Dict[str, str]
    isEnabled: bool
    location: AzureLocation
    logicalSkus: Optional[List[str]] = None
    subtype: ResourceSubtype
    targetCount: int
    type: ResourceType


class PoolResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domainUserCredentials: Optional[DomainUserCredentials] = None
    hotPoolSettings: Optional[HotPoolSettings] = None
    poolGroupName: str
    provisioningStatus: Optional[ProvisioningStatusResult] = None
    tags: Optional[Dict[str, str]] = None
    userGroupName: Optional[str] = None
    vmSpecs: VMSpecs


class PoolSettingsBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branchName: Optional[str] = None
    devContainerPath: Optional[str] = None
    pools: Optional[List[Pool]] = None
    repoId: Optional[str] = None
    storageType: Optional[StorageType] = None


class RPSubscriptionProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountOwner: Optional[SubscriptionAccountOwner] = None
    additionalProperties: Optional[SubscriptionAdditionalProperties] = None
    locationPlacementId: Optional[str] = None
    managedByTenants: Optional[List[StringStringKeyValuePair]] = None
    quotaId: Optional[str] = None
    registeredFeatures: Optional[List[StringStringKeyValuePair]] = None
    tenantId: Optional[UUID] = None


class ResourceUsageDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    compute: Optional[List[ComputeUsageDetail]] = None
    storage: Optional[List[StorageUsageDetail]] = None


class SecretDataBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    type: Optional[SecretType] = None
    value: Optional[constr(min_length=1, max_length=65536)] = None


class SecretFilterBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Optional[SecretFilterType] = None
    value: Optional[constr(min_length=1, max_length=200)] = None


class UnfilteredCloudEnvironmentResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accessToken: Optional[str] = None
    active: Optional[datetime] = None
    autoShutdownDelayMinutes: Optional[int] = None
    billableOwnerType: Optional[BillableOwnerType] = None
    clientUsage: Optional[ClientUsageSession] = None
    connection: Optional[ConnectionInfoBody] = None
    container: Optional[ContainerInfoBody] = None
    containerImage: Optional[str] = None
    createFromPrebuild: Optional[bool] = None
    created: Optional[datetime] = None
    displayStorageUtilizationInKb: Optional[bool] = None
    exportedBlobUrl: Optional[str] = None
    failoverDetails: Optional[FailoverDetails] = None
    features: Optional[Dict[str, str]] = None
    friendlyName: Optional[str] = None
    gitStatus: Optional[GitStatus] = None
    id: Optional[str] = None
    lastStateUpdateReason: Optional[str] = None
    lastUsed: Optional[datetime] = None
    location: Optional[str] = None
    organizationId: Optional[str] = None
    ownerId: Optional[str] = None
    planId: Optional[str] = None
    platform: Optional[str] = None
    portForwardingConnection: Optional[ConnectionInfoBody] = None
    prebuildType: Optional[str] = None
    recentFolders: Optional[List[str]] = None
    resourceTier: Optional[ConsumerType] = None
    runtimeConstraints: Optional[RuntimeConstraintsBody] = None
    seed: Optional[SeedInfoBody] = None
    skuDisplayName: Optional[str] = None
    skuName: Optional[str] = None
    state: Optional[str] = None
    storageUtilizationInKb: Optional[int] = None
    subscriptionData: Optional[SubscriptionData] = None
    templateStatus: Optional[str] = None
    type: Optional[str] = None
    updated: Optional[datetime] = None


class UpdateUserSecretsRequestBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    secrets: Optional[List[SecretDataBody]] = None


class VMConnectionInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectionType: Optional[VMConnectionType] = None
    liveShareWorkspaceId: Optional[str] = None


class VMResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connection: Optional[VMConnectionInfo] = None
    provisioningStatus: Optional[ProvisioningStatusResult] = None
    status: Optional[VMStatus] = None


class ApiV1TenantTenantIdPoolPoolNameVmGetResponse(RootModel[List[VMResult]]):
    root: List[VMResult]


class CloudEnvironmentResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accessToken: Optional[str] = None
    active: Optional[datetime] = None
    autoShutdownDelayMinutes: Optional[int] = None
    billableOwnerType: Optional[BillableOwnerType] = None
    clientUsage: Optional[ClientUsageSession] = None
    connection: Optional[ConnectionInfoBody] = None
    container: Optional[ContainerInfoBody] = None
    containerImage: Optional[str] = None
    createFromPrebuild: Optional[bool] = None
    created: Optional[datetime] = None
    displayStorageUtilizationInKb: Optional[bool] = None
    exportedBlobUrl: Optional[str] = None
    failoverDetails: Optional[FailoverDetails] = None
    features: Optional[Dict[str, str]] = None
    friendlyName: Optional[str] = None
    gitStatus: Optional[GitStatus] = None
    id: Optional[str] = None
    lastStateUpdateReason: Optional[str] = None
    lastUsed: Optional[datetime] = None
    location: Optional[str] = None
    organizationId: Optional[str] = None
    ownerId: Optional[str] = None
    planId: Optional[str] = None
    platform: Optional[str] = None
    portForwardingConnection: Optional[ConnectionInfoBody] = None
    prebuildType: Optional[str] = None
    recentFolders: Optional[List[str]] = None
    resourceTier: Optional[ConsumerType] = None
    runtimeConstraints: Optional[RuntimeConstraintsBody] = None
    seed: Optional[SeedInfoBody] = None
    skuDisplayName: Optional[str] = None
    skuName: Optional[str] = None
    state: Optional[str] = None
    storageUtilizationInKb: Optional[int] = None
    subscriptionData: Optional[SubscriptionData] = None
    templateStatus: Optional[str] = None
    type: Optional[str] = None
    updated: Optional[datetime] = None


class CreateCloudEnvironmentBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    analyticsTrackingId: Optional[str] = None
    autoShutdownDelayMinutes: Optional[int] = None
    billableOwner: Optional[BillableOwnerBody] = None
    connection: Optional[ConnectionInfoBody] = None
    containerImage: Optional[str] = None
    createAsPrebuild: Optional[bool] = None
    devContainerJson: Optional[str] = None
    devContainerPath: Optional[str] = None
    experimentalFeatures: Optional[ExperimentalFeaturesBody] = None
    features: Optional[Dict[str, str]] = None
    friendlyName: str
    gitHubApiUrl: Optional[str] = None
    gitHubAppUrl: Optional[str] = None
    gitHubPfsAuthEndpoint: Optional[str] = None
    githubEnvironmentEndpoint: Optional[str] = None
    hasDevcontainerJson: Optional[bool] = None
    identity: Optional[IdentityBody] = None
    label: Optional[str] = None
    location: Optional[str] = None
    netmonCorrelationData: Optional[NetmonCorrelationDataBody] = None
    personalization: Optional[PersonalizationInfoBody] = None
    planId: Optional[str] = None
    platform: Optional[str] = None
    runtimeConstraints: Optional[RuntimeConstraintsBody] = None
    secrets: Optional[List[SecretDataBody]] = None
    seed: Optional[SeedInfoBody] = None
    skuName: Optional[str] = None
    testAccount: Optional[bool] = None
    type: str
    userTier: Optional[str] = None
    workingDirectory: Optional[str] = None


class CreateEnvironmentPoolResourceBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environmentOptions: Optional[PrebuildEnvironmentOptions] = None
    secrets: Optional[List[SecretDataBody]] = None


class EnvironmentUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    endState: Optional[CloudEnvironmentState] = None
    id: Optional[str] = None
    resourceUsage: Optional[ResourceUsageDetail] = None
    sku: Optional[Sku] = None


class PlanResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    identity: Optional[PlanResourceIdentity] = None
    location: Optional[str] = None
    name: Optional[str] = None
    properties: Optional[PlanResourceProperties] = None
    provisioningState: Optional[str] = None
    tags: Optional[Dict[str, str]] = None
    type: Optional[str] = None


class PlanResourceList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Optional[List[PlanResource]] = None


class RPSubscriptionNotification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    properties: Optional[RPSubscriptionProperties] = None
    registrationDate: Optional[datetime] = None
    state: Optional[str] = None


class ScopedCreateSecretBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    filters: Optional[List[SecretFilterBody]] = None
    notes: Optional[constr(min_length=0, max_length=200)] = None
    scope: Optional[SecretScope] = None
    secretName: Optional[
        constr(pattern=r'^(?!CLOUDENV.*$)[a-zA-Z_][a-zA-Z0-9_]{0,199}$')
    ] = None
    type: Optional[SecretType] = None
    value: Optional[constr(min_length=1, max_length=65536)] = None


class ScopedSecretResultBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filters: Optional[List[SecretFilterBody]] = None
    id: Optional[UUID] = None
    lastModified: Optional[datetime] = None
    notes: Optional[str] = None
    scope: Optional[SecretScope] = None
    secretName: Optional[str] = None
    type: Optional[SecretType] = None


class ScopedUpdateSecretBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    filters: Optional[List[SecretFilterBody]] = None
    notes: Optional[constr(min_length=0, max_length=200)] = None
    scope: Optional[SecretScope] = None
    secretName: Optional[
        constr(pattern=r'^(?!CLOUDENV.*$)[a-zA-Z_][a-zA-Z0-9_]{0,199}$')
    ] = None
    value: Optional[constr(min_length=1, max_length=65536)] = None


class ApiV1EnvironmentsGetResponse(RootModel[List[CloudEnvironmentResult]]):
    root: List[CloudEnvironmentResult]


class ApiV1SasGetResponse(RootModel[List[ScopedSecretResultBody]]):
    root: List[ScopedSecretResultBody]


class ApiV1SecretsGetResponse(RootModel[List[ScopedSecretResultBody]]):
    root: List[ScopedSecretResultBody]


class BillSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    billGenerationTime: Optional[datetime] = None
    environmentId: Optional[str] = None
    id: Optional[str] = None
    location: Optional[AzureLocation] = None
    partitionKey: Optional[str] = None
    periodEnd: Optional[datetime] = None
    periodStart: Optional[datetime] = None
    plan: Optional[VsoPlanInfo] = None
    usage: Optional[Dict[str, float]] = None
    usageDetail: Optional[List[EnvironmentUsage]] = None
